# Generated by Django 5.0.6 on 2024-10-13 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('source_file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('tag_searched', models.CharField(max_length=255)),
                ('block_record', models.TextField()),
                ('location_of_tag', models.CharField(max_length=255)),
                ('date_of_search', models.DateTimeField(auto_now_add=True)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('partial', 'Partial Match')], max_length=10)),
                ('other', models.CharField(blank=True, max_length=255)),
                ('line_id', models.CharField(blank=True, max_length=255, null=True)),
                ('search_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
